# Generated by Django 4.2.4 on 2023-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(choices=[('JK', 'Junior Kindergarten'), ('SK', 'Senior Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade_level',
            field=models.CharField(choices=[('JK', 'Junior Kindergarten'), ('SK', 'Senior Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2),
        ),
    ]
