# Generated by Django 4.2.4 on 2023-12-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_teacher_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='classroom',
            name='classrooms',
            field=models.ManyToManyField(to='api.student'),
        ),
    ]
