# Generated by Django 4.2.4 on 2023-12-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_classrooms_classroom_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('value', models.IntegerField(choices=[(-2, 'Needs Improvements'), (-1, 'Satisfactory'), (1, 'Good'), (2, 'Excellent')])),
                ('student_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentclassroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='student_scores',
        ),
        migrations.DeleteModel(
            name='SudentFeedback',
        ),
        migrations.AddField(
            model_name='studentclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom'),
        ),
        migrations.AddField(
            model_name='studentclassroom',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customfeedback'),
        ),
        migrations.AddField(
            model_name='studentclassroom',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='received_feedback',
            field=models.ManyToManyField(blank=True, to='api.studentfeedback'),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
		),
		migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(through='api.StudentClassroom', to='api.student'),
		),
    ]
