# Generated by Django 4.2.4 on 2023-12-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teacher_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassroom',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='student_classroom',
        ),
        migrations.AlterField(
            model_name='studentclassroom',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
